name: Developer Setup
port: 5000
smtp:
  host: smtp.qq.com
  port: 587
  user:
  pwd:
imap:
  network: tcp
  timeout: 10m
  mailServers:
    - host: imap.qq.com
      port: 993
      auth:
        user:
        pwd:
      timeout: 0s
      flush_time: 10s
mongo:
  url: mongodb://127.0.0.1:27017
  db: mail_go
  user:
  password:
  grid_prefix: mail
  collection: mail_user

