// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mail.proto

package response

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Mail struct {
	MessageId            int32        `protobuf:"varint,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	Subject              string       `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	To                   []string     `protobuf:"bytes,3,rep,name=to,proto3" json:"to,omitempty"`
	From                 []string     `protobuf:"bytes,4,rep,name=from,proto3" json:"from,omitempty"`
	Text                 []*Mail_Body `protobuf:"bytes,5,rep,name=text,proto3" json:"text,omitempty"`
	Attachment           *Mail_Body   `protobuf:"bytes,6,opt,name=attachment,proto3" json:"attachment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Mail) Reset()         { *m = Mail{} }
func (m *Mail) String() string { return proto.CompactTextString(m) }
func (*Mail) ProtoMessage()    {}
func (*Mail) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0}
}

func (m *Mail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mail.Unmarshal(m, b)
}
func (m *Mail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mail.Marshal(b, m, deterministic)
}
func (m *Mail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mail.Merge(m, src)
}
func (m *Mail) XXX_Size() int {
	return xxx_messageInfo_Mail.Size(m)
}
func (m *Mail) XXX_DiscardUnknown() {
	xxx_messageInfo_Mail.DiscardUnknown(m)
}

var xxx_messageInfo_Mail proto.InternalMessageInfo

func (m *Mail) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *Mail) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Mail) GetTo() []string {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Mail) GetFrom() []string {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Mail) GetText() []*Mail_Body {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *Mail) GetAttachment() *Mail_Body {
	if m != nil {
		return m.Attachment
	}
	return nil
}

type Mail_Body struct {
	ContentType          string   `protobuf:"bytes,1,opt,name=contentType,proto3" json:"contentType,omitempty"`
	Fds                  string   `protobuf:"bytes,2,opt,name=fds,proto3" json:"fds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mail_Body) Reset()         { *m = Mail_Body{} }
func (m *Mail_Body) String() string { return proto.CompactTextString(m) }
func (*Mail_Body) ProtoMessage()    {}
func (*Mail_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0, 0}
}

func (m *Mail_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mail_Body.Unmarshal(m, b)
}
func (m *Mail_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mail_Body.Marshal(b, m, deterministic)
}
func (m *Mail_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mail_Body.Merge(m, src)
}
func (m *Mail_Body) XXX_Size() int {
	return xxx_messageInfo_Mail_Body.Size(m)
}
func (m *Mail_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_Mail_Body.DiscardUnknown(m)
}

var xxx_messageInfo_Mail_Body proto.InternalMessageInfo

func (m *Mail_Body) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *Mail_Body) GetFds() string {
	if m != nil {
		return m.Fds
	}
	return ""
}

func init() {
	proto.RegisterType((*Mail)(nil), "response.Mail")
	proto.RegisterType((*Mail_Body)(nil), "response.Mail.Body")
}

func init() { proto.RegisterFile("mail.proto", fileDescriptor_7cda5f053e74676b) }

var fileDescriptor_7cda5f053e74676b = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x31, 0x4b, 0x03, 0x41,
	0x10, 0x85, 0xd9, 0xbb, 0x4d, 0xf4, 0x26, 0x20, 0x32, 0x36, 0x8b, 0x58, 0x2c, 0x36, 0x6e, 0xb5,
	0x85, 0xe9, 0x2c, 0xed, 0x2c, 0x6c, 0x16, 0xff, 0xc0, 0xe6, 0x6e, 0xa2, 0x91, 0xec, 0xce, 0x71,
	0x3b, 0x82, 0xf9, 0xef, 0x16, 0x72, 0x8b, 0xc1, 0x34, 0xe9, 0xde, 0x7c, 0x7c, 0xf0, 0x78, 0x03,
	0x90, 0xe2, 0x6e, 0xef, 0xc7, 0x89, 0x85, 0xf1, 0x72, 0xa2, 0x32, 0x72, 0x2e, 0x74, 0xff, 0xa3,
	0x40, 0xbf, 0xc6, 0xdd, 0x1e, 0xef, 0xa0, 0x4b, 0x54, 0x4a, 0x7c, 0xa7, 0x97, 0xc1, 0x28, 0xab,
	0xdc, 0x22, 0xfc, 0x03, 0x34, 0x70, 0x51, 0xbe, 0x36, 0x9f, 0xd4, 0x8b, 0x69, 0xac, 0x72, 0x5d,
	0x38, 0x9e, 0x78, 0x05, 0x8d, 0xb0, 0x69, 0x6d, 0xeb, 0xba, 0xd0, 0x08, 0x23, 0x82, 0xde, 0x4e,
	0x9c, 0x8c, 0xae, 0xa4, 0x66, 0x7c, 0x00, 0x2d, 0xf4, 0x2d, 0x66, 0x61, 0x5b, 0xb7, 0x7a, 0xbc,
	0xf1, 0xc7, 0x76, 0x3f, 0x37, 0xfb, 0x67, 0x1e, 0x0e, 0xa1, 0x0a, 0xb8, 0x06, 0x88, 0x22, 0xb1,
	0xff, 0x48, 0x94, 0xc5, 0x2c, 0xad, 0x3a, 0xa7, 0x9f, 0x68, 0xb7, 0x4f, 0xa0, 0x67, 0x86, 0x16,
	0x56, 0x3d, 0x67, 0xa1, 0x2c, 0x6f, 0x87, 0x91, 0xea, 0x86, 0x2e, 0x9c, 0x22, 0xbc, 0x86, 0x76,
	0x3b, 0x94, 0xbf, 0x05, 0x73, 0xdc, 0x2c, 0xeb, 0x3f, 0xd6, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x70, 0x71, 0xe3, 0x17, 0x1d, 0x01, 0x00, 0x00,
}
