// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mail.proto

package response

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Mail struct {
	MessageId            string     `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	Subject              string     `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	To                   []*Address `protobuf:"bytes,3,rep,name=to,proto3" json:"to,omitempty"`
	From                 []*Address `protobuf:"bytes,4,rep,name=from,proto3" json:"from,omitempty"`
	Text                 []*Body    `protobuf:"bytes,5,rep,name=text,proto3" json:"text,omitempty"`
	Attachment           *Body      `protobuf:"bytes,6,opt,name=attachment,proto3" json:"attachment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Mail) Reset()         { *m = Mail{} }
func (m *Mail) String() string { return proto.CompactTextString(m) }
func (*Mail) ProtoMessage()    {}
func (*Mail) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0}
}

func (m *Mail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mail.Unmarshal(m, b)
}
func (m *Mail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mail.Marshal(b, m, deterministic)
}
func (m *Mail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mail.Merge(m, src)
}
func (m *Mail) XXX_Size() int {
	return xxx_messageInfo_Mail.Size(m)
}
func (m *Mail) XXX_DiscardUnknown() {
	xxx_messageInfo_Mail.DiscardUnknown(m)
}

var xxx_messageInfo_Mail proto.InternalMessageInfo

func (m *Mail) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *Mail) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Mail) GetTo() []*Address {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Mail) GetFrom() []*Address {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Mail) GetText() []*Body {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *Mail) GetAttachment() *Body {
	if m != nil {
		return m.Attachment
	}
	return nil
}

type Body struct {
	ContentType          string   `protobuf:"bytes,1,opt,name=contentType,proto3" json:"contentType,omitempty"`
	MainBody             []byte   `protobuf:"bytes,2,opt,name=mainBody,proto3" json:"mainBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Body) Reset()         { *m = Body{} }
func (m *Body) String() string { return proto.CompactTextString(m) }
func (*Body) ProtoMessage()    {}
func (*Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{1}
}

func (m *Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Body.Unmarshal(m, b)
}
func (m *Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Body.Marshal(b, m, deterministic)
}
func (m *Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Body.Merge(m, src)
}
func (m *Body) XXX_Size() int {
	return xxx_messageInfo_Body.Size(m)
}
func (m *Body) XXX_DiscardUnknown() {
	xxx_messageInfo_Body.DiscardUnknown(m)
}

var xxx_messageInfo_Body proto.InternalMessageInfo

func (m *Body) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *Body) GetMainBody() []byte {
	if m != nil {
		return m.MainBody
	}
	return nil
}

type Address struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{2}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Address) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*Mail)(nil), "response.Mail")
	proto.RegisterType((*Body)(nil), "response.Body")
	proto.RegisterType((*Address)(nil), "response.Address")
}

func init() { proto.RegisterFile("mail.proto", fileDescriptor_7cda5f053e74676b) }

var fileDescriptor_7cda5f053e74676b = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x3f, 0x4b, 0xc4, 0x40,
	0x10, 0xc5, 0x49, 0x6e, 0xbd, 0x3f, 0x73, 0x22, 0x38, 0xd5, 0x22, 0x16, 0x31, 0x20, 0x5c, 0x95,
	0x42, 0x0b, 0x6b, 0xc5, 0xc6, 0xc2, 0x26, 0xf8, 0x05, 0xe6, 0x92, 0x51, 0x23, 0xb7, 0x3b, 0x21,
	0x3b, 0x82, 0xf7, 0x5d, 0xfd, 0x30, 0x92, 0x35, 0xf1, 0x52, 0x78, 0xdd, 0xbe, 0xf7, 0x7e, 0x0c,
	0xfb, 0x1e, 0x80, 0xa3, 0x66, 0x57, 0xb4, 0x9d, 0xa8, 0xe0, 0xb2, 0xe3, 0xd0, 0x8a, 0x0f, 0x9c,
	0x7f, 0x27, 0x60, 0x9e, 0xa9, 0xd9, 0xe1, 0x25, 0xac, 0x1c, 0x87, 0x40, 0x6f, 0xfc, 0x54, 0xdb,
	0x24, 0x4b, 0x36, 0xab, 0xf2, 0x60, 0xa0, 0x85, 0x45, 0xf8, 0xdc, 0x7e, 0x70, 0xa5, 0x36, 0x8d,
	0xd9, 0x28, 0xf1, 0x0a, 0x52, 0x15, 0x3b, 0xcb, 0x66, 0x9b, 0xf5, 0xcd, 0x79, 0x31, 0xde, 0x2d,
	0xee, 0xeb, 0xba, 0xe3, 0x10, 0xca, 0x54, 0x05, 0xaf, 0xc1, 0xbc, 0x76, 0xe2, 0xac, 0x39, 0x06,
	0xc5, 0x18, 0x73, 0x30, 0xca, 0x5f, 0x6a, 0x4f, 0x22, 0x76, 0x76, 0xc0, 0x1e, 0xa4, 0xde, 0x97,
	0x31, 0xc3, 0x02, 0x80, 0x54, 0xa9, 0x7a, 0x77, 0xec, 0xd5, 0xce, 0xb3, 0xe4, 0x1f, 0x72, 0x42,
	0xe4, 0x8f, 0x60, 0x7a, 0x0f, 0x33, 0x58, 0x57, 0xe2, 0x95, 0xbd, 0xbe, 0xec, 0x5b, 0x1e, 0xfa,
	0x4d, 0x2d, 0xbc, 0x80, 0xa5, 0xa3, 0xc6, 0xf7, 0x74, 0xac, 0x78, 0x5a, 0xfe, 0xe9, 0xfc, 0x0e,
	0x16, 0xc3, 0x57, 0x11, 0xc1, 0x78, 0x72, 0xe3, 0x85, 0xf8, 0xee, 0xc7, 0xa1, 0xdf, 0x78, 0x1c,
	0x67, 0x90, 0xdb, 0x79, 0x9c, 0xfb, 0xf6, 0x27, 0x00, 0x00, 0xff, 0xff, 0x8b, 0xd4, 0x6c, 0xa8,
	0x7c, 0x01, 0x00, 0x00,
}
